### PR TITLE
fix(webpack): remove runtime insertion hack from webpack 3 or below e…

### LINKED ISSUE #157: Aurelia Plugin doesn't use Webpack "entry" items as expected
**I'm submitting a bug report**

* **Library Version:**
3.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

**Current behavior:**
Aurelia currently only prepends special runtime files to the first `entry` defined in your Webpack config file.
```
'aurelia-webpack-plugin/runtime/empty-entry',
'aurelia-webpack-plugin/runtime/pal-loader-entry',
```

Snippet from `node_modules\aurelia-webpack-plugin\dist\AureliaPlugin.js`
```js
addEntry(options, modules) {
	let webpackEntry = options.entry;
	let entries = Array.isArray(modules) ? modules : [modules];
	if (typeof webpackEntry == "object" && !Array.isArray(webpackEntry)) {
		// There are multiple entries defined in the config
		// Unless there was a particular configuration, we modify the first one
		// (note that JS enumerates props in the same order they were declared)
		// Modifying the first one only plays nice with the common pattern
		// `entry: { main, vendor }` some people use.
		let ks = this.options.entry || Object.keys(webpackEntry)[0];
		if (!Array.isArray(ks)) {
			ks = [ks];
		}
		ks.forEach(k => {
			webpackEntry[k] = entries.concat(webpackEntry[k])
		});
	} else {
		options.entry = entries.concat(webpackEntry);
	}
}
```

* **What is the motivation / use case for changing the behavior?**

Before Webpack 4, the fix/workaround above probably made sense. However, since vendoring is not handled in `entry` anymore, I think we can remove this without much fuss. I think ultimately it would help Aurelia be more predictable.

Making this change would require a major version bump as it breaks / changes behaviour.

```js
addEntry(options, modules) {
	let webpackEntry = options.entry;
	let entries = Array.isArray(modules) ? modules : [modules];
	if (typeof webpackEntry == "object" && !Array.isArray(webpackEntry)) {
		for (let k in webpackEntry) {
			if (!webpackEntry.hasOwnProperty(k)) {
				continue;
			}
			let entry = webpackEntry[k];
			if (!Array.isArray(entry)) {
				entry = [entry];
			}
			webpackEntry[k] = entries.concat(entry)
		}
	} else {
		options.entry = entries.concat(webpackEntry);
	}
}
```

### PR DESCRIPTION
**Pull request by silbinarywolf**
fix(webpack): remove runtime insertion hack from webpack 3 or below era, wherein only the first "entry" item had the runtime appended to it.

This was originally implemented to avoid adding the runtime to the secondary "vendor" entry. Using "vendor" entry points which is no longer recommended for Webpack 4 and up.

Fixes #157

### CODE REVIEW

**Comment by silbinarywolf** [comment]
All this changes seem reasonable to me! I'll work on actioning this within the next few days!

Thanks for the feedback :)

**Comment by silbinarywolf** [comment]
Seems like it's not really possible to update the wiki with a PR, as per:
https://stackoverflow.com/a/11481887/5013410

I have however, put up a branch here with the copy change:
https://github.com/silbinarywolf/aurelia-webpack-plugin-wiki/pull/1

A maintainer will need to merge this in by pulling it down manually.

**Comment by silbinarywolf** [comment]
@jods4 Let me know if the above changes are all OK or if they need further effort :)

File: src/AureliaPlugin.ts [hunk 1]
```diff
@@ -215,17 +215,29 @@ export class AureliaPlugin {
...
+          webpackEntry[k] = entries.concat(webpackEntry[k])
+        });
+      } else {
+        // Add runtime to each entry
+        for (let k in webpackEntry) {
+          if (!webpackEntry.hasOwnProperty(k)) {
+            continue;
+          }
+          let entry = webpackEntry[k];
+          if (!Array.isArray(entry)) {
```
Comment (jods4) [inline src/AureliaPlugin.ts]: Nit: this is not required. `Array::concat` handles non-array parameters properly.

File: src/AureliaPlugin.ts [hunk 2]
```diff
@@ -215,17 +215,29 @@ export class AureliaPlugin {
...
-      for (let k in webpackEntry) {
-        if (!webpackEntry.hasOwnProperty(k)) {
-          continue;
+    if (typeof webpackEntry === "object" && !Array.isArray(webpackEntry)) {
+      if (this.options.entry) {
+        // Add runtime only to the entries defined on this plugin
+        let ks = this.options.entry;
+        if (!Array.isArray(ks)) ks = [ks];
+        ks.forEach(k => {
+          if (webpackEntry[k] === undefined) {
```
Comment (jods4) [inline src/AureliaPlugin.ts]: Nice, you went the extra mile by adding this safety check. 👍

**Comment by jods4** [comment]
LGTM.
I will update the wiki once this is published.

File: src/AureliaPlugin.ts (hunk 1 above)
Comment (jakebiress) [reply src/AureliaPlugin.ts]: Ah I'll keep this in mind for the future, cheers :)

**Comment by jakebiress** [comment]
@EisenbergEffect It's all ready :)

**Comment by silbinarywolf** [comment]
@EisenbergEffect It's all ready :)

**Comment by EisenbergEffect** [comment]
@jods4 Want to take a final look or are we ready to merge?

**Comment by jods4** [comment]
@EisenbergEffect LGTM
